default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>
# test:
#   <<: *default
#   database: <%= ENV.fetch("DATABASE_TEST_NAME", "app_test") %>
#
# production:
#   <<: *default
#   database: myapp_production
#   username: myapp
#   password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
